#https://gallery.ecr.aws/lambda/nodejs
#That image is ARM64, but your EC2 machine is most likely x86_64 (Intel/AMD),  
# so Docker cannot execute /bin/sh inside the container during build.

#FROM public.ecr.aws/lambda/nodejs:20.2025.10.13.17-arm64
FROM public.ecr.aws/lambda/nodejs:20-x86_64

WORKDIR ${LAMBDA_TASK_ROOT}

#COPY package*.json ./
COPY package.json .

RUN npm install

COPY . .

RUN npm run build

CMD ["server.handler"]